# Generated by Django 4.2b1 on 2024-02-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.IntegerField()),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deactive', 'Deactive')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('rate_unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrugEye',
            fields=[
                ('TradeName', models.CharField(max_length=255)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('ScName', models.CharField(max_length=255)),
                ('HOWMUCH', models.IntegerField()),
                ('Unit', models.CharField(max_length=100)),
                ('CLASSIFICATION', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('drugs', models.ManyToManyField(to='Prescription.drug')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='DrugEye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescription.drugeye'),
        ),
    ]
