# Generated by Django 4.2b1 on 2024-03-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('new', 'New')], max_length=100),
        ),
    ]
