# Generated by Django 4.2b1 on 2024-02-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('otp', models.PositiveIntegerField()),
            ],
        ),
    ]
