# Generated by Django 4.2b1 on 2024-02-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
