# Generated by Django 4.2b1 on 2024-02-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0003_session_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
