# Generated by Django 4.2b1 on 2024-03-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDIInteraction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('drug1_id', models.CharField(max_length=50)),
                ('drug2_id', models.CharField(max_length=50)),
                ('drug1_name', models.CharField(max_length=255)),
                ('drug2_name', models.CharField(max_length=255)),
                ('interaction_type', models.CharField(max_length=1000)),
            ],
        ),
    ]
