# Generated by Django 4.2b1 on 2024-04-01 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_fname', message='First name must contain only letters.', regex='^[A-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_lname', message='Last name must contain only letters.', regex='^[A-Za-z]+$')]),
        ),
    ]
