# Generated by Django 4.2b1 on 2024-04-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_fname_alter_user_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customtoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
