# Generated by Django 4.2b1 on 2024-02-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_doctor_license_number'),
        ('Doctor', '0003_doctor_image'),
    ]

    operations = [
    ]
